defmodule DtuApp.Emails.SunDownEmailTest do
  @moduledoc """
  Tests for `DtuApp.Emails.SunDownEmail.render/2`.

  The sun-down email is the rich end-of-day summary: a 2x2 stat
  grid (today yield / yesterday yield / peak / peak yesterday), an
  inline SVG of today's power curve, and a dashboard CTA. The
  chart SVG is generated by the producer (`Notifications.SunDown`,
  wired in Task 7) and passed in via `payload.chart_svg`; this
  module just embeds it verbatim when present and degrades to a
  "No chart available" paragraph when nil.

  The producer-localised body carries the catalog's
  `"Today: %{today_kwh} kWh%{yield_diff}, peak %{peak_w} W%{peak_diff}."`
  string — the same msgid the producer builds via
  `body_for/2`. Task 9 adds de/fr translations for the email-specific
  labels (`Today's yield`, `Peak power`, `Today's power curve`,
  `No chart available`, `Today's yield`, `View dashboard`,
  `You're getting this email because you enabled end-of-day summaries.`)
  plus the producer's `vs yesterday` / `same as yesterday` fragments.
  The drift-guard below anchors on the producer-localised body so
  the data path's translation flows are exercised end-to-end
  (mirroring `SunUpEmailTest`).
  """

  use DtuApp.DataCase, async: true

  alias DtuApp.Accounts.User
  alias DtuApp.Emails.SunDownEmail

  # The SunDown email module owns its own stat-panel labels
  # (`gettext("Today's yield")`, `gettext("Peak power")`, etc.) and
  # builds `body_html` from the payload's numeric fields, NOT from
  # `payload.body`. So the drift-guard anchors on a representative
  # panel label rather than the producer's body string — same
  # pattern as `SunUpEmailTest` but applied to the labels the email
  # module actually renders.
  @sun_down_yield_label_msgid "Today's yield"

  setup do
    user = %User{email: "u@example.com", locale: "en"}
    payload = %{
      title: "Sun down",
      body: ["Today: 12.4 kWh, peak 3,250 W."],
      event: "sun_down",
      today_yield_kwh: 12.4,
      yesterday_yield_kwh: 10.1,
      peak_power_w: 3250,
      peak_yesterday_w: 2840,
      chart_svg: "<svg viewBox=\"0 0 800 280\"></svg>",
      dashboard_path: "/dashboard"
    }
    {:ok, user: user, payload: payload}
  end

  describe "render/2 — basic contract" do
    test "returns {html, text} where html starts with <html", %{user: user, payload: p} do
      {html, text} = SunDownEmail.render(user, p)
      assert is_binary(html)
      assert html =~ "<html"
      assert is_binary(text)
    end

    test "html includes the title from the payload", %{user: user, payload: p} do
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ "Sun down"
    end

    test "html contains all four stat panels (today / yesterday yields + peaks)", %{user: user, payload: p} do
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ "12.4"
      assert html =~ "10.1"
      assert html =~ "3,250"
      assert html =~ "2,840"
    end

    test "html includes the chart svg when chart_svg is present", %{user: user, payload: p} do
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ "<svg"
    end

    test "html includes the dashboard button label and url", %{user: user, payload: p} do
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ "/dashboard"
      assert html =~ "View dashboard"
    end

    test "text body includes the title and the stat values", %{user: user, payload: p} do
      {_html, text} = SunDownEmail.render(user, p)
      assert text =~ "Sun down"
      assert text =~ "12.4"
      assert text =~ "10.1"
      assert text =~ "3,250"
      assert text =~ "2,840"
      assert text =~ "/dashboard"
    end
  end

  describe "render/2 — <html lang> attribute" do
    test "matches the user's locale (de)", %{payload: p} do
      user = %User{email: "u@example.com", locale: "de"}
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ ~s(<html lang="de")
    end

    test "matches the user's locale (fr)", %{payload: p} do
      user = %User{email: "u@example.com", locale: "fr"}
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ ~s(<html lang="fr")
    end

    test "falls back to lang=en when user.locale is nil", %{payload: p} do
      user = %User{email: "u@example.com", locale: nil}
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ ~s(<html lang="en")
    end
  end

  describe "render/2 — chart fallback" do
    test "degrades to 'No chart available' when chart_svg is nil", %{user: user, payload: p} do
      {html, _} = SunDownEmail.render(user, %{p | chart_svg: nil})
      assert html =~ "No chart available"
      refute html =~ "<svg"
    end
  end

  describe "render/2 — missing-yesterday fallback" do
    test "renders '—' when yesterday yield + peak are missing", %{user: user, payload: p} do
      {html, _} =
        SunDownEmail.render(user, %{
          p
          | yesterday_yield_kwh: nil,
            peak_yesterday_w: nil
        })

      assert html =~ "—"
    end

    test "renders the 'same as yesterday' label when today equals yesterday",
         %{user: user, payload: p} do
      {html, _} =
        SunDownEmail.render(user, %{
          p
          | today_yield_kwh: 10.1,
            yesterday_yield_kwh: 10.1
        })

      assert html =~ "same as yesterday"
    end
  end

  describe "render/2 — localised body (producer-data gettext drift guard)" do
    # Anchored on the email-module-localised panel label that the
    # SunDown email actually renders (the email module builds its
    # own `body_html` from the numeric payload fields, NOT from
    # `payload.body`, so the producer's body string never reaches
    # the rendered HTML — we exercise the same catalog path through
    # a label the email owns).
    #
    # Same pattern as `SunUpEmailTest`: we build the expected label
    # via `Gettext.with_locale/2` + `Gettext.gettext/3` against
    # the same catalog line the email module uses, so a translation
    # update flows through automatically without re-pinning literal
    # strings. If the catalog line ever moves or the email's render
    # path ever drops/escapes the panel label, these tests fail.
    test "renders the English (source) yield label for locale=en", %{user: user, payload: p} do
      localised_label =
        Gettext.with_locale(DtuAppWeb.Gettext, "en", fn ->
          Gettext.gettext(DtuAppWeb.Gettext, @sun_down_yield_label_msgid)
        end)

      {html, _} = SunDownEmail.render(user, p)
      assert html =~ localised_label
    end

    test "renders the German yield label for locale=de", %{payload: p} do
      user = %User{email: "u@example.com", locale: "de"}

      localised_label =
        Gettext.with_locale(DtuAppWeb.Gettext, "de", fn ->
          Gettext.gettext(DtuAppWeb.Gettext, @sun_down_yield_label_msgid)
        end)

      {html, _} = SunDownEmail.render(user, p)
      assert html =~ localised_label
    end

    test "renders the French yield label for locale=fr", %{payload: p} do
      user = %User{email: "u@example.com", locale: "fr"}

      localised_label =
        Gettext.with_locale(DtuAppWeb.Gettext, "fr", fn ->
          Gettext.gettext(DtuAppWeb.Gettext, @sun_down_yield_label_msgid)
        end)

      {html, _} = SunDownEmail.render(user, p)
      assert html =~ localised_label
    end
  end
end
