defmodule DtuApp.Emails.SunDownEmailTest do
  @moduledoc """
  Tests for `DtuApp.Emails.SunDownEmail.render/2`.

  The sun-down email is the rich end-of-day summary: a 2x2 stat
  grid (today yield / yesterday yield / peak / peak yesterday), an
  inline SVG of today's power curve, and a dashboard CTA. The
  chart SVG is generated by the producer (`Notifications.SunDown`,
  wired in Task 7) and passed in via `payload.chart_svg`; this
  module just embeds it verbatim when present and degrades to a
  "No chart available" paragraph when nil.

  The producer-localised strings (`"Today's yield"`, `"Peak power"`,
  `"Yesterday"`, `"vs yesterday"`, `"same as yesterday"`,
  `"Today's power curve"`, `"No chart available"`, `"View dashboard"`,
  `"You're getting this email because you enabled end-of-day summaries."`)
  are added to the de/fr catalogs by Task 9 — not yet. Until then,
  the locale-distinct signal we can reliably assert is the
  `<html lang="...">` attribute; the de/fr catalog translations will
  flow through automatically once Task 9 lands (mirroring the
  drift-guard pattern from `SunUpEmailTest`).
  """

  use DtuApp.DataCase, async: true

  alias DtuApp.Accounts.User
  alias DtuApp.Emails.SunDownEmail

  setup do
    user = %User{email: "u@example.com", locale: "en"}
    payload = %{
      title: "Sun down",
      body: ["Today: 12.4 kWh, peak 3,250 W."],
      event: "sun_down",
      today_yield_kwh: 12.4,
      yesterday_yield_kwh: 10.1,
      peak_power_w: 3250,
      peak_yesterday_w: 2840,
      chart_svg: "<svg viewBox=\"0 0 800 280\"></svg>",
      dashboard_path: "/dashboard"
    }
    {:ok, user: user, payload: payload}
  end

  describe "render/2 — basic contract" do
    test "returns {html, text} where html starts with <html", %{user: user, payload: p} do
      {html, text} = SunDownEmail.render(user, p)
      assert is_binary(html)
      assert html =~ "<html"
      assert is_binary(text)
    end

    test "html includes the title from the payload", %{user: user, payload: p} do
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ "Sun down"
    end

    test "html contains all four stat panels (today / yesterday yields + peaks)", %{user: user, payload: p} do
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ "12.4"
      assert html =~ "10.1"
      assert html =~ "3,250"
      assert html =~ "2,840"
    end

    test "html includes the chart svg when chart_svg is present", %{user: user, payload: p} do
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ "<svg"
    end

    test "html includes the dashboard button label and url", %{user: user, payload: p} do
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ "/dashboard"
      assert html =~ "View dashboard"
    end

    test "text body includes the title and the stat values", %{user: user, payload: p} do
      {_html, text} = SunDownEmail.render(user, p)
      assert text =~ "Sun down"
      assert text =~ "12.4"
      assert text =~ "10.1"
      assert text =~ "3,250"
      assert text =~ "2,840"
      assert text =~ "/dashboard"
    end
  end

  describe "render/2 — <html lang> attribute" do
    test "matches the user's locale (de)", %{payload: p} do
      user = %User{email: "u@example.com", locale: "de"}
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ ~s(<html lang="de")
    end

    test "matches the user's locale (fr)", %{payload: p} do
      user = %User{email: "u@example.com", locale: "fr"}
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ ~s(<html lang="fr")
    end

    test "falls back to lang=en when user.locale is nil", %{payload: p} do
      user = %User{email: "u@example.com", locale: nil}
      {html, _} = SunDownEmail.render(user, p)
      assert html =~ ~s(<html lang="en")
    end
  end

  describe "render/2 — chart fallback" do
    test "degrades to 'No chart available' when chart_svg is nil", %{user: user, payload: p} do
      {html, _} = SunDownEmail.render(user, %{p | chart_svg: nil})
      assert html =~ "No chart available"
      refute html =~ "<svg"
    end
  end

  describe "render/2 — missing-yesterday fallback" do
    test "renders '—' when yesterday yield + peak are missing", %{user: user, payload: p} do
      {html, _} =
        SunDownEmail.render(user, %{
          p
          | yesterday_yield_kwh: nil,
            peak_yesterday_w: nil
        })

      assert html =~ "—"
    end

    test "renders the 'same as yesterday' label when today equals yesterday",
         %{user: user, payload: p} do
      {html, _} =
        SunDownEmail.render(user, %{
          p
          | today_yield_kwh: 10.1,
            yesterday_yield_kwh: 10.1
        })

      assert html =~ "same as yesterday"
    end
  end
end
