defmodule DtuApp.Emails.SunDownEmailTest do
  @moduledoc """
  Tests for `DtuApp.Emails.SunDownEmail.render/2`.

  The sun-down email is the rich end-of-day summary: a 2x2 stat
  grid (today yield / yesterday yield / peak / peak yesterday), an
  inline SVG of today's power curve, and a dashboard CTA. The
  chart SVG is generated by the producer (`Notifications.SunDown`,
  wired in Task 7) and passed in via `payload.chart_svg`; this
  module just embeds it verbatim when present and degrades to a
  "No chart available" paragraph when nil.

  The producer-localised body carries the catalog's
  `"Today: %{today_kwh} kWh%{yield_diff}, peak %{peak_w} W%{peak_diff}."`
  string — the same msgid the producer builds via
  `body_for/2`. Task 9 adds de/fr translations for the email-specific
  labels (`Today's yield`, `Peak power`, `Today's power curve`,
  `No chart available`, `Today's yield`, `View dashboard`,
  `You're getting this email because you enabled end-of-day summaries.`)
  plus the producer's `vs yesterday` / `same as yesterday` fragments.
  The drift-guard below anchors on the producer-localised body so
  the data path's translation flows are exercised end-to-end
  (mirroring `SunUpEmailTest`).
  """

  use DtuApp.DataCase, async: true

  alias DtuApp.Accounts.User
  alias DtuApp.Emails.SunDownEmail

  # The SunDown email module owns its own stat-panel labels
  # (`gettext("Today's yield")`, `gettext("Peak power")`, etc.) and
  # builds `body_html` from the payload's numeric fields, NOT from
  # `payload.body`. So the drift-guard anchors on a representative
  # panel label rather than the producer's body string — same
  # pattern as `SunUpEmailTest` but applied to the labels the email
  # module actually renders.
  @sun_down_yield_label_msgid "Today's yield"

  setup do
    user = %User{email: "u@example.com", locale: "en"}

    payload = %{
      title: "Sun down",
      body: ["Today: 12.4 kWh, peak 3,250 W."],
      event: "sun_down",
      today_yield_kwh: 12.4,
      yesterday_yield_kwh: 10.1,
      peak_power_w: 3250,
      peak_yesterday_w: 2840,
      chart_svg: "<svg viewBox=\"0 0 800 280\"></svg>",
      dashboard_path: "/dashboard"
    }

    {:ok, user: user, payload: payload}
  end

  describe "render/2 — basic contract" do
    test "returns {html, text, attachments} where html starts with <html", %{
      user: user,
      payload: p
    } do
      {html, text, attachments} = SunDownEmail.render(user, p)
      assert is_binary(html)
      assert html =~ "<html"
      assert is_binary(text)
      assert is_list(attachments)
    end

    test "html includes the title from the payload", %{user: user, payload: p} do
      {html, _, _} = SunDownEmail.render(user, p)
      assert html =~ "Sun down"
    end

    test "html contains all four stat panels (today / yesterday yields + peaks)", %{
      user: user,
      payload: p
    } do
      {html, _, _} = SunDownEmail.render(user, p)
      assert html =~ "12.4"
      assert html =~ "10.1"
      assert html =~ "3,250"
      assert html =~ "2,840"
    end

    test "html includes the dashboard button label and url", %{user: user, payload: p} do
      {html, _, _} = SunDownEmail.render(user, p)
      assert html =~ "/dashboard"
      assert html =~ "View dashboard"
    end

    test "text body includes the title and the stat values", %{user: user, payload: p} do
      {_html, text, _attachments} = SunDownEmail.render(user, p)
      assert text =~ "Sun down"
      assert text =~ "12.4"
      assert text =~ "10.1"
      assert text =~ "3,250"
      assert text =~ "2,840"
      assert text =~ "/dashboard"
    end
  end

  describe "render/2 — chart as cid-attached PNG" do
    # The chart must render in Gmail, which strips inline `<svg>` from
    # the email HTML body. The fix is to convert the SVG to a PNG and
    # attach it as a `cid:`-referenced image so the HTML body contains
    # a single `<img src="cid:chart@sundo">` reference. Tests exercise
    # the success path via an injected fake CLI (drains stdin, emits a
    # 1x1 PNG to stdout) and the fallback path by setting the CLI path
    # to `nil`.

    # 1x1 transparent PNG — smallest valid PNG, the canonical byte
    # sequence (89 50 4E 47 0D 0A 1A 0A + IHDR + IDAT + IEND). Stored as
    # a list of integers so the module attribute is unambiguous (the
    # `<<...>>` syntax for module attributes has bitten this pattern in
    # the past, and the byte values themselves don't change between
    # runs).
    @png_1x1_byte_list [
      137,
      80,
      78,
      71,
      13,
      10,
      26,
      10,
      0,
      0,
      0,
      13,
      73,
      72,
      68,
      82,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      1,
      8,
      6,
      0,
      0,
      0,
      31,
      21,
      196,
      137,
      0,
      0,
      0,
      11,
      73,
      68,
      65,
      84,
      24,
      87,
      99,
      248,
      255,
      255,
      63,
      0,
      5,
      254,
      2,
      254,
      164,
      171,
      207,
      7,
      0,
      0,
      0,
      0,
      73,
      69,
      78,
      68,
      174,
      66,
      96,
      130
    ]

    setup do
      # Write the fake CLI to a tmp file so each test gets its own.
      fake =
        Path.join(
          System.tmp_dir!(),
          "rsvg-convert-fake-#{System.unique_integer([:positive])}.sh"
        )

      # rsvg-convert real API: positional input file + `-o output.png`.
      # The fake CLI accepts that exact shape, writes the same byte
      # sequence to the `-o` path, and exits 0.
      octal =
        @png_1x1_byte_list
        |> Enum.map(&("\\" <> Integer.to_string(&1, 8)))
        |> Enum.join()

      script =
        "#!/bin/sh\n" <>
          "# fake rsvg-convert: copy the positional input to /dev/null,\n" <>
          "# write a fixed 1x1 PNG to the -o output, exit 0.\n" <>
          "INPUT=\"$@\"\n" <>
          "# the input is the last arg; find it\n" <>
          "for arg in \"$@\"; do\n" <>
          "  if [ -f \"$arg\" ]; then INPUT=\"$arg\"; fi\n" <>
          "done\n" <>
          "OUT=\"\"\n" <>
          "while [ $# -gt 0 ]; do\n" <>
          "  case \"$1\" in\n" <>
          "    -o) OUT=\"$2\"; shift 2;;\n" <>
          "    *) shift;;\n" <>
          "  esac\n" <>
          "done\n" <>
          "printf '" <> octal <> "' > \"$OUT\"\n"

      File.write!(fake, script)
      File.chmod!(fake, 0o755)

      on_exit(fn -> File.rm(fake) end)

      {:ok, fake_cli: fake, png_bytes: :erlang.list_to_binary(@png_1x1_byte_list)}
    end

    test "html contains <img src=\"cid:chart@sundo\">, no raw <svg> (success path)",
         %{user: user, payload: p, fake_cli: fake} do
      Application.put_env(:dtu_app, :swoosh_email_chart_cli, fake)

      {html, _text, attachments} = SunDownEmail.render(user, p)

      assert html =~ ~s(<img src="cid:chart@sundo")
      refute html =~ "<svg"
      assert length(attachments) == 1
    end

    test "attachments list contains a single Swoosh.Attachment image/png with PNG bytes",
         %{user: user, payload: p, fake_cli: fake, png_bytes: png_bytes} do
      Application.put_env(:dtu_app, :swoosh_email_chart_cli, fake)

      {_html, _text, attachments} = SunDownEmail.render(user, p)

      assert length(attachments) == 1
      [att] = attachments
      assert att.__struct__ == Swoosh.Attachment
      assert att.content_type == "image/png"
      assert att.data == png_bytes
    end

    test "text body never contains <img> or <svg> on the success path",
         %{user: user, payload: p, fake_cli: fake} do
      Application.put_env(:dtu_app, :swoosh_email_chart_cli, fake)

      {_html, text, _attachments} = SunDownEmail.render(user, p)

      refute text =~ "<img"
      refute text =~ "<svg"
      # But the text body MUST mention the chart so the user has a hint.
      assert text =~ "power curve" or text =~ ~s(today)
    end

    test "fallback path: html is a plain paragraph + URL, no attachment, when CLI missing",
         %{user: user, payload: p} do
      Application.put_env(:dtu_app, :swoosh_email_chart_cli, nil)

      {html, text, attachments} = SunDownEmail.render(user, p)

      assert html =~ "View today's power curve"
      assert html =~ "/dashboard"
      refute html =~ "<svg"
      refute html =~ "<img"

      assert text =~ "View today's power curve"
      assert text =~ "/dashboard"
      refute text =~ "<svg"
      refute text =~ "<img"

      assert attachments == []
    end

    test "chart_svg nil still produces the empty-state fallback (regression guard)",
         %{user: user, payload: p, fake_cli: fake} do
      Application.put_env(:dtu_app, :swoosh_email_chart_cli, fake)

      {html, _text, attachments} = SunDownEmail.render(user, %{p | chart_svg: nil})

      assert html =~ "No chart available"
      refute html =~ "<svg"
      refute html =~ "<img"
      assert attachments == []
    end

    # Regression: some `rsvg-convert` builds on Alpine 3.19 exit 0 but
    # write 0 bytes to the `-o` path (the PNG ends up on stdout instead).
    # Pre-fix the email shipped with `attachment.data == ""` — the
    # `cid:chart@sundo` reference was present but the MIME image part
    # had an empty body, so Gmail rendered a broken-image icon and the
    # text body LIED with "Today's power curve is attached as an image."
    # Post-fix this falls through to the dashboard-link fallback (no
    # attachment, no `cid:` reference, no misleading text).
    test "falls back to the dashboard-link path when rsvg-convert exits 0 but writes 0 bytes",
         %{user: user, payload: p} do
      fake =
        Path.join(
          System.tmp_dir!(),
          "rsvg-convert-empty-#{System.unique_integer([:positive])}.sh"
        )

      # Same arg-parse shape as the success-path fake, but truncate
      # the output file to 0 bytes instead of writing PNG bytes.
      # Exit 0, no error output — exactly what a "PNG went to stdout
      # by accident" rsvg-convert invocation looks like to the caller.
      script =
        "#!/bin/sh\n" <>
          "OUT=\"\"\n" <>
          "while [ $# -gt 0 ]; do\n" <>
          "  case \"$1\" in\n" <>
          "    -o) OUT=\"$2\"; shift 2;;\n" <>
          "    *) shift;;\n" <>
          "  esac\n" <>
          "done\n" <>
          ": > \"$OUT\"\n"

      File.write!(fake, script)
      File.chmod!(fake, 0o755)
      on_exit(fn -> File.rm(fake) end)

      Application.put_env(:dtu_app, :swoosh_email_chart_cli, fake)

      {html, text, attachments} = SunDownEmail.render(user, p)

      # No cid-attachment should ship — empty bytes would render as a
      # broken image in Gmail and the text body would falsely claim an
      # image is attached.
      assert attachments == []

      refute html =~ ~s(<img src="cid:),
             "html must not reference a cid-attachment when the PNG bytes are empty"

      # Fallback text — both the HTML body and the plain text body
      # point the user at the dashboard URL.
      assert html =~ "View today's power curve"
      assert html =~ "/dashboard"
      assert text =~ "View today's power curve"
      assert text =~ "/dashboard"

      # And critically: the misleading "attached as an image" line
      # from the cid-attachment path must NOT appear.
      refute text =~ "attached as an image"
    end
  end

  describe "render/2 — <html lang> attribute" do
    test "matches the user's locale (de)", %{payload: p} do
      user = %User{email: "u@example.com", locale: "de"}
      {html, _, _} = SunDownEmail.render(user, p)
      assert html =~ ~s(<html lang="de")
    end

    test "matches the user's locale (fr)", %{payload: p} do
      user = %User{email: "u@example.com", locale: "fr"}
      {html, _, _} = SunDownEmail.render(user, p)
      assert html =~ ~s(<html lang="fr")
    end

    test "falls back to lang=en when user.locale is nil", %{payload: p} do
      user = %User{email: "u@example.com", locale: nil}
      {html, _, _} = SunDownEmail.render(user, p)
      assert html =~ ~s(<html lang="en")
    end
  end

  describe "render/2 — chart fallback (empty-state)" do
    test "degrades to 'No chart available' when chart_svg is nil", %{user: user, payload: p} do
      {html, _, attachments} = SunDownEmail.render(user, %{p | chart_svg: nil})
      assert html =~ "No chart available"
      refute html =~ "<svg"
      refute html =~ "<img"
      assert attachments == []
    end
  end

  describe "render/2 — missing-yesterday fallback" do
    test "renders '—' when yesterday yield + peak are missing", %{user: user, payload: p} do
      {html, _, _} =
        SunDownEmail.render(user, %{
          p
          | yesterday_yield_kwh: nil,
            peak_yesterday_w: nil
        })

      assert html =~ "—"
    end

    test "renders the 'same as yesterday' label when today equals yesterday",
         %{user: user, payload: p} do
      {html, _, _} =
        SunDownEmail.render(user, %{
          p
          | today_yield_kwh: 10.1,
            yesterday_yield_kwh: 10.1
        })

      assert html =~ "same as yesterday"
    end
  end

  describe "render/2 — localised body (producer-data gettext drift guard)" do
    # Anchored on the email-module-localised panel label that the
    # SunDown email actually renders (the email module builds its
    # own `body_html` from the numeric payload fields, NOT from
    # `payload.body`, so the producer's body string never reaches
    # the rendered HTML — we exercise the same catalog path through
    # a label the email owns).
    #
    # Same pattern as `SunUpEmailTest`: we build the expected label
    # via `Gettext.with_locale/2` + `Gettext.gettext/3` against
    # the same catalog line the email module uses, so a translation
    # update flows through automatically without re-pinning literal
    # strings. If the catalog line ever moves or the email's render
    # path ever drops/escapes the panel label, these tests fail.
    test "renders the English (source) yield label for locale=en", %{user: user, payload: p} do
      localised_label =
        Gettext.with_locale(DtuAppWeb.Gettext, "en", fn ->
          Gettext.gettext(DtuAppWeb.Gettext, @sun_down_yield_label_msgid)
        end)

      {html, _, _} = SunDownEmail.render(user, p)
      assert html =~ localised_label
    end

    test "renders the German yield label for locale=de", %{payload: p} do
      user = %User{email: "u@example.com", locale: "de"}

      localised_label =
        Gettext.with_locale(DtuAppWeb.Gettext, "de", fn ->
          Gettext.gettext(DtuAppWeb.Gettext, @sun_down_yield_label_msgid)
        end)

      {html, _, _} = SunDownEmail.render(user, p)
      assert html =~ localised_label
    end

    test "renders the French yield label for locale=fr", %{payload: p} do
      user = %User{email: "u@example.com", locale: "fr"}

      localised_label =
        Gettext.with_locale(DtuAppWeb.Gettext, "fr", fn ->
          Gettext.gettext(DtuAppWeb.Gettext, @sun_down_yield_label_msgid)
        end)

      {html, _, _} = SunDownEmail.render(user, p)
      assert html =~ localised_label
    end
  end
end
