defmodule DtuApp.Emails.SunDownEmail do
  @moduledoc """
  Email body for `sun_down` events. The richest of the three
  notification emails — four stat panels (today yield / yesterday yield /
  peak power / peak yesterday), a chart of today's power curve (rendered
  as a `cid:`-attached PNG so it works in Gmail and other clients that
  strip inline `<svg>`), and a dashboard CTA.

  The chart SVG is generated by the producer
  (`DtuApp.Notifications.SunDown`) and passed in via `payload.chart_svg`;
  this module converts it to PNG via `chart_attachment/1` and embeds the
  image via an `<img src="cid:chart@sundo">` reference. When the
  converter (`rsvg-convert`, librsvg) is missing or fails, the module
  falls back to a "View today's power curve on the dashboard" plain-text
  paragraph — the email still goes out, just without the chart. When
  the producer couldn't build a chart at all (no devices / no readings),
  the existing "No chart available" empty-state is preserved.

  The producer is responsible for the pre-translated title / body; this
  module owns the email-specific copy (greeting, button label, note) and
  stamps the `<html lang>` attribute from `user.locale`. The whole
  `Layout.render/1` call is wrapped in `Gettext.with_locale/2` so the
  email-specific `gettext/1` calls resolve against the same catalog the
  producer used.
  """

  use Gettext, backend: DtuAppWeb.Gettext

  alias DtuApp.Emails.Layout

  # Stable cid used by both the `<img src="cid:...">` reference in the
  # HTML body and the `Swoosh.Attachment`'s Content-ID header. The
  # suffix is intentional so MIME parsers that require a
  # `<message-id-style>` cid (per RFC 2392) accept it; Swoosh generates
  # the matching `Content-ID: <chart@sundo>` header from the value you
  # pass to `Swoosh.Attachment.put_content_id/2`.
  @chart_cid "chart@sundo"

  @doc """
  Convert the producer's SVG to a PNG suitable for cid-attachment.

  Returns:

    * `{:ok, png_binary}` when the SVG was successfully converted.
    * `:unavailable` when the converter CLI (`rsvg-convert`, from
      librsvg) is missing or the conversion exits non-zero. Callers
      must treat this as a recoverable degradation — the email goes
      out, but without the chart.

  The CLI path is resolved via
  `Application.get_env(:dtu_app, :swoosh_email_chart_cli, System.find_executable("rsvg-convert"))`,
  so tests can inject a fake (success path) or `nil` (fallback path)
  without touching the host filesystem.
  """
  # The PNG signature every valid PNG starts with (RFC 2083). Any
  # bytes without this prefix at offset 0 are not a PNG — likely
  # an `rsvg-convert` failure mode that leaked stderr or wrote
  # a partial/empty placeholder to `-o`.
  @png_signature <<137, 80, 78, 71, 13, 10, 26, 10>>

  # The IEND chunk (RFC 2083) is the last chunk in every structurally
  # complete PNG: 4-byte length (always 0) + "IEND" type + 4-byte CRC
  # (always `0xAE 0x42 0x60 0x82`, the CRC of the literal "IEND"
  # string). A PNG without a terminating IEND chunk is missing its
  # end-of-image marker — PNG decoders bail mid-decode and Gmail
  # renders the cid-attachment as a flat grey rectangle exactly the
  # size of the chart slot (the user-visible 2026-09-18 regression on
  # tag 2026-09-17-7: rsvg-convert exited 0 with a PNG-shaped blob
  # whose first 8 bytes were the PNG signature and whose size was
  # over the 1024-byte floor, but whose IDAT chunks were truncated
  # before the IEND terminator was written).
  @png_iend_chunk <<0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82>>

  # Healthy floor for an 800-px-wide chart SVG. The empty-state
  # placeholder compresses to ~1.4 KB; the real chart compresses to
  # ~6 KB. Anything under this either means rsvg-convert bailed
  # silently mid-encode (truncated IHDR/IDAT), or the chart is so
  # sparse it would render as effectively blank — both produce a
  # broken-image experience in Gmail.
  @min_png_byte_size 1024

  @spec chart_attachment(String.t()) :: {:ok, binary()} | :unavailable
  def chart_attachment(svg) when is_binary(svg) do
    cli_path =
      Application.get_env(
        :dtu_app,
        :swoosh_email_chart_cli,
        System.find_executable("rsvg-convert")
      )

    case cli_path do
      nil ->
        :unavailable

      cli when is_binary(cli) ->
        # rsvg-convert accepts an SVG file path as its positional
        # argument and writes the converted PNG to stdout. We pass
        # `-w 800` to fix the output width to match the chart's
        # viewBox so the email image renders at the same visual size
        # as the in-page chart. Elixir's `System.cmd/3` has no
        # `stdin_data` option, so we write the SVG to a temp file,
        # invoke the converter, and clean up.
        tmp_in =
          Path.join(System.tmp_dir!(), "sundo-svg-#{System.unique_integer([:positive])}.svg")

        tmp_out =
          Path.join(System.tmp_dir!(), "sundo-png-#{System.unique_integer([:positive])}.png")

        try do
          File.write!(tmp_in, svg)

          {_stdout, 0} =
            System.cmd(cli, ["-w", "800", "-f", "png", "-o", tmp_out, tmp_in],
              stderr_to_stdout: true
            )

          # Defense-in-depth on the PNG output. `rsvg-convert` can
          # exit 0 and still produce a broken attachment:
          #
          #   * writes 0 bytes to `-o` (some Alpine 3.19 builds emit
          #     the PNG to stdout instead — the captured `_stdout`
          #     above has it, but `-o` ends up empty)
          #   * writes a non-PNG payload (truncated output, or a
          #     stderr fragment captured into `-o` via some CLI
          #     mis-parsing)
          #   * writes a pathologically-small PNG (encoder aborted
          #     mid-write, or the chart is so sparse the rendered
          #     image would be effectively blank)
          #
          # Pre-fix each of these arrived at Gmail as a valid
          # `Content-Transfer-Encoding: base64` image/png part —
          # either with an empty body (case 1) or with bytes that
          # don't decode to a usable image (cases 2/3). In every
          # case the `<img src="cid:chart@sundo">` rendered as a
          # broken-image icon AND the text body LIED with
          # "Today's power curve is attached as an image."
          # Reject all three at the source so the email falls
          # through to the dashboard-link fallback and the text
          # body tells the truth.
          png = File.read!(tmp_out)
          reason = classify_png_failure(png)

          case reason do
            nil ->
              {:ok, png}

            _ ->
              require Logger

              Logger.warning(
                "[sun_down_email] rsvg-convert #{cli} produced a #{reason} PNG " <>
                  "(#{byte_size(png)} bytes); falling back to dashboard-link chart"
              )

              :unavailable
          end
        rescue
          _ -> :unavailable
        catch
          _, _ -> :unavailable
        after
          File.rm(tmp_in)
          File.rm(tmp_out)
        end
    end
  end

  def render(%{locale: locale}, payload) do
    Gettext.with_locale(DtuAppWeb.Gettext, locale || "en", fn ->
      {chart_html, chart_text_line, chart_attachments} = chart_block(payload)

      # The text body has to carry the panel values (today yield,
      # yesterday yield, peak power, peak yesterday) as plain text.
      # We don't pull the panel table HTML into the text body — that
      # would produce literal "View Source" gibberish in every
      # text/plain viewer (the original bug). Instead, render a
      # parallel plain-text panel summary and pass it through `:body`,
      # with `text_extra` carrying the chart note. The chart note
      # appears ONCE in the final text body — Layout.text_body/8
      # appends text_extra to body when text_extra is non-empty, so
      # passing the chart line via :body would duplicate it.
      text_body_lines = text_panels(payload)

      {html, text, layout_attachments} =
        Layout.render(
          title: payload.title,
          greeting: gettext("Hi,"),
          body: text_body_lines,
          body_html: [
            panels_html(payload),
            chart_label_html(),
            chart_html
          ],
          text_extra: chart_text_lines(chart_text_line),
          button: %{
            label: gettext("View dashboard"),
            url: dashboard_url(payload)
          },
          note: gettext("You're getting this email because you enabled end-of-day summaries."),
          lang: locale || "en"
        )

      {html, text, layout_attachments ++ chart_attachments}
    end)
  end

  # `text_extra` is the new plain-text bridge between SunDownEmail and
  # Layout.render/1. Wrap the chart's text line in a list (Layout accepts
  # `[]` when there's nothing extra to add) so the chart-empty-state
  # path stays aligned with the chart-text-success path.
  @spec chart_text_lines(String.t() | nil) :: [String.t()]
  defp chart_text_lines(nil), do: []
  defp chart_text_lines(line) when is_binary(line), do: [line]

  # Plain-text counterpart to `panels_html/1`. Two short lines: today's
  # yield / peak, each with yesterday's value and the delta in
  # parentheses. Used by the text body so the email still carries the
  # numbers when the HTML view is rendered by an HTML-only client.
  @spec text_panels(map()) :: [String.t()]
  defp text_panels(p) do
    today_yield = format_kwh(p[:today_yield_kwh] || p["today_yield_kwh"])
    yest_yield = format_kwh(p[:yesterday_yield_kwh] || p["yesterday_yield_kwh"])
    peak = format_w(p[:peak_power_w] || p["peak_power_w"])
    yest_peak = format_w(p[:peak_yesterday_w] || p["peak_yesterday_w"])
    today_kwh = p[:today_yield_kwh] || p["today_yield_kwh"]
    yest_kwh = p[:yesterday_yield_kwh] || p["yesterday_yield_kwh"]
    today_w = p[:peak_power_w] || p["peak_power_w"]
    yest_w = p[:peak_yesterday_w] || p["peak_yesterday_w"]

    [
      "#{gettext("Today's yield")}: #{today_yield} kWh (#{gettext("Yesterday")}: #{yest_yield} kWh, #{delta(today_kwh, yest_kwh, "kWh")}).",
      "#{gettext("Peak power")}: #{peak} W (#{gettext("Yesterday")}: #{yest_peak} W, #{delta(today_w, yest_w, "W")})."
    ]
  end

  # Render the chart as a `cid:`-attached PNG when conversion succeeds,
  # fall back to a plain `<p>` + dashboard link when it doesn't. Returns
  # a triple `{html_fragment, text_line, attachments}`:
  #
  #   * success: `<img src="cid:chart@sundo" ...>` HTML, a short text
  #     mention ("Today's power curve is attached as an image"), and
  #     one Swoosh.Attachment with the PNG bytes.
  #   * fallback: `<p>` with the dashboard URL + sentence, the same line
  #     in text, no attachments.
  #   * empty-state (no chart_svg in payload): "No chart available"
  #     paragraph (HTML only), no text line, no attachments.
  @spec chart_block(map()) :: {String.t(), String.t() | nil, [struct()]}
  defp chart_block(payload) do
    case payload[:chart_svg] || payload["chart_svg"] do
      nil ->
        {"<p style=\"font-size:13px;color:#64748b;\">#{escape(gettext("No chart available"))}</p>",
         nil, []}

      svg ->
        case chart_attachment(svg) do
          {:ok, png} ->
            html =
              ~s(<img src="cid:#{@chart_cid}" alt="#{escape(gettext("Today's power curve"))}" ) <>
                ~s(style="display:block;width:100%;max-width:560px;height:auto;border:0;" />)

            text = gettext("Today's power curve is attached as an image.")

            {html, text,
             [
               Swoosh.Attachment.new(
                 {:data, png},
                 filename: "chart.png",
                 content_type: "image/png",
                 type: :inline,
                 cid: @chart_cid
               )
             ]}

          :unavailable ->
            # Fallback: plain `<p>` with the dashboard URL — text body
            # gets the same sentence. No attachment.
            dashboard_url = dashboard_url(payload)

            html =
              ~s(<p style="font-size:13px;color:#64748b;margin:0 0 12px 0;">) <>
                escape(gettext("View today's power curve on the dashboard:")) <>
                ~s( <a href="#{escape(dashboard_url)}" target="_blank" style="color:#10b981;text-decoration:underline;">#{escape(dashboard_url)}</a></p>)

            text =
              gettext("View today's power curve on the dashboard:") <>
                " " <> dashboard_url

            {html, text, []}
        end
    end
  end

  # Four panels in a 2x2 grid (table-based for email-client safety).
  # The numbers come pre-formatted; the only thing we escape here is
  # the user-facing copy (gettext strings can carry `&`, `<`, `>`
  # in translated form).
  defp panels_html(p) do
    today_yield = format_kwh(p[:today_yield_kwh] || p["today_yield_kwh"])
    yest_yield = format_kwh(p[:yesterday_yield_kwh] || p["yesterday_yield_kwh"])
    peak = format_w(p[:peak_power_w] || p["peak_power_w"])
    yest_peak = format_w(p[:peak_yesterday_w] || p["peak_yesterday_w"])
    today_kwh = p[:today_yield_kwh] || p["today_yield_kwh"]
    yest_kwh = p[:yesterday_yield_kwh] || p["yesterday_yield_kwh"]
    today_w = p[:peak_power_w] || p["peak_power_w"]
    yest_w = p[:peak_yesterday_w] || p["peak_yesterday_w"]

    """
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 16px 0;">
      <tr>
        <td width="50%" style="padding:8px 4px;">
          <div style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">#{escape(gettext("Today's yield"))}</div>
          <div style="font-size:22px;font-weight:700;color:#18181b;margin-top:2px;">#{escape(today_yield)} <span style="font-size:14px;font-weight:500;color:#64748b;">kWh</span></div>
          <div style="font-size:12px;color:#64748b;margin-top:2px;">#{escape(gettext("Yesterday"))}: #{escape(yest_yield)} kWh (#{escape(delta(today_kwh, yest_kwh, "kWh"))})</div>
        </td>
        <td width="50%" style="padding:8px 4px;">
          <div style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">#{escape(gettext("Peak power"))}</div>
          <div style="font-size:22px;font-weight:700;color:#18181b;margin-top:2px;">#{escape(peak)} <span style="font-size:14px;font-weight:500;color:#64748b;">W</span></div>
          <div style="font-size:12px;color:#64748b;margin-top:2px;">#{escape(gettext("Yesterday"))}: #{escape(yest_peak)} W (#{escape(delta(today_w, yest_w, "W"))})</div>
        </td>
      </tr>
    </table>
    """
  end

  defp chart_label_html do
    """
    <p style="font-size:11px;color:#475569;text-transform:uppercase;letter-spacing:0.05em;margin:16px 0 4px 0;">
      #{escape(gettext("Today's power curve"))}
    </p>
    """
  end

  # Yield / peak delta. Either side nil → "—" (the producer couldn't
  # compute yesterday's value). Equal → "same as yesterday". Above →
  # `+diff`, below → bare diff. Format mirrors
  # `Notifications.SunDown.compare/3`.
  defp delta(nil, _, _), do: "—"
  defp delta(_, nil, _), do: "—"

  defp delta(today, yesterday, unit) when is_number(today) and is_number(yesterday) do
    cond do
      today == yesterday ->
        gettext("same as yesterday")

      true ->
        diff = today - yesterday
        sign = if diff > 0, do: "+", else: ""
        "#{sign}#{format_diff(diff, unit)} #{gettext("vs yesterday")}"
    end
  end

  defp format_diff(diff, "kWh"), do: diff |> Float.round(1) |> Float.to_string()
  defp format_diff(diff, "W"), do: diff |> round() |> Integer.to_string()

  # `12.4` for numbers, "—" for nil (no yesterday baseline).
  defp format_kwh(nil), do: "—"

  defp format_kwh(v) when is_number(v),
    do: v |> Float.round(1) |> Float.to_string()

  # `3,250` for numbers (thousands separator), "—" for nil.
  defp format_w(nil), do: "—"

  defp format_w(v) when is_number(v),
    do: v |> round() |> Integer.to_string() |> add_thousands_sep()

  defp add_thousands_sep(s) do
    s
    |> String.graphemes()
    |> Enum.reverse()
    |> Enum.chunk_every(3)
    |> Enum.join(",")
    |> String.reverse()
  end

  defp dashboard_url(%{dashboard_path: path}),
    do: DtuAppWeb.Endpoint.url() <> (path || "/dashboard")

  defp dashboard_url(_), do: DtuAppWeb.Endpoint.url() <> "/dashboard"

  # Small HTML escaper — gettext msgids ship as source strings but
  # .po translations can contain arbitrary text. Layout.escape/1
  # is private, so we keep a local copy here.
  defp escape(s) when is_binary(s),
    do:
      s
      |> String.replace("&", "&amp;")
      |> String.replace("<", "&lt;")
      |> String.replace(">", "&gt;")

  defp escape(_), do: ""

  # Returns a short failure tag when the bytes don't look like a
  # usable PNG, or `nil` when they're acceptable. Four classes —
  # `:empty`, `:no_png_signature`, `:too_small`, `:truncated` — line
  # up with the failure modes described at the call site; the tag
  # is the only thing logged, so an operator triaging a "chart
  # missing" report knows which rsvg-convert install to inspect.
  @spec classify_png_failure(binary()) :: atom() | nil
  defp classify_png_failure(png) when png == <<>>, do: :empty
  defp classify_png_failure(png) when byte_size(png) < @min_png_byte_size, do: :too_small

  defp classify_png_failure(png) do
    cond do
      not valid_png_signature?(png) -> :no_png_signature
      not ends_with_iend_chunk?(png) -> :truncated
      true -> nil
    end
  end

  defp valid_png_signature?(png),
    do: :binary.part(png, 0, 8) == @png_signature

  # RFC 2083: every structurally-complete PNG ends with the 12-byte
  # IEND chunk `00 00 00 00 49 45 4E 44 AE 42 60 82`. A file that
  # starts with the PNG signature but doesn't terminate with IEND is
  # missing its end-of-image marker — PNG decoders refuse the file,
  # Gmail renders a flat grey rectangle in the img slot, and the
  # `<img src="cid:chart@sundo">` element collapses silently. The
  # check is O(1) (a 12-byte `binary.part/3` tail comparison) so it's
  # safe to run on every chart conversion.
  defp ends_with_iend_chunk?(png) when byte_size(png) >= 12 do
    iend_offset = byte_size(png) - 12
    :binary.part(png, iend_offset, 12) == @png_iend_chunk
  end

  defp ends_with_iend_chunk?(_), do: false
end
