defmodule DtuApp.Emails.SunDownEmail do
  @moduledoc """
  Email body for `sun_down` events. The richest of the three
  notification emails — four stat panels (today yield / yesterday
  yield / peak power / peak yesterday), an inline SVG of today's
  power curve, and a dashboard CTA.

  The chart SVG is generated by the producer
  (`DtuApp.Notifications.SunDown`, wired in Task 7) and passed in
  via `payload.chart_svg`; this module just embeds it verbatim when
  present and degrades to a `gettext("No chart available")`
  paragraph when nil. The producer is also responsible for the
  pre-translated title / body; this module owns the email-specific
  copy (greeting, button label, note) and stamps the `<html lang>`
  attribute from `user.locale`. The whole `Layout.render/1` call is
  wrapped in `Gettext.with_locale/2` so the email-specific
  `gettext/1` calls resolve against the same catalog the producer
  used.
  """

  use Gettext, backend: DtuAppWeb.Gettext

  alias DtuApp.Emails.Layout

  def render(%{locale: locale}, payload) do
    Gettext.with_locale(DtuAppWeb.Gettext, locale || "en", fn ->
      Layout.render(
        title: payload.title,
        greeting: gettext("Hi,"),
        body_html: [
          panels_html(payload),
          chart_label_html(),
          chart_html(payload)
        ],
        button: %{
          label: gettext("View dashboard"),
          url: dashboard_url(payload)
        },
        note:
          gettext(
            "You're getting this email because you enabled end-of-day summaries."
          ),
        lang: locale || "en"
      )
    end)
  end

  # Four panels in a 2x2 grid (table-based for email-client safety).
  # The numbers come pre-formatted; the only thing we escape here is
  # the user-facing copy (gettext strings can carry `&`, `<`, `>`
  # in translated form).
  defp panels_html(p) do
    today_yield = format_kwh(p[:today_yield_kwh] || p["today_yield_kwh"])
    yest_yield = format_kwh(p[:yesterday_yield_kwh] || p["yesterday_yield_kwh"])
    peak = format_w(p[:peak_power_w] || p["peak_power_w"])
    yest_peak = format_w(p[:peak_yesterday_w] || p["peak_yesterday_w"])
    today_kwh = p[:today_yield_kwh] || p["today_yield_kwh"]
    yest_kwh = p[:yesterday_yield_kwh] || p["yesterday_yield_kwh"]
    today_w = p[:peak_power_w] || p["peak_power_w"]
    yest_w = p[:peak_yesterday_w] || p["peak_yesterday_w"]

    """
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 16px 0;">
      <tr>
        <td width="50%" style="padding:8px 4px;">
          <div style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">#{escape(gettext("Today's yield"))}</div>
          <div style="font-size:22px;font-weight:700;color:#18181b;margin-top:2px;">#{escape(today_yield)} <span style="font-size:14px;font-weight:500;color:#64748b;">kWh</span></div>
          <div style="font-size:12px;color:#64748b;margin-top:2px;">#{escape(gettext("Yesterday"))}: #{escape(yest_yield)} kWh (#{escape(delta(today_kwh, yest_kwh, "kWh"))})</div>
        </td>
        <td width="50%" style="padding:8px 4px;">
          <div style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">#{escape(gettext("Peak power"))}</div>
          <div style="font-size:22px;font-weight:700;color:#18181b;margin-top:2px;">#{escape(peak)} <span style="font-size:14px;font-weight:500;color:#64748b;">W</span></div>
          <div style="font-size:12px;color:#64748b;margin-top:2px;">#{escape(gettext("Yesterday"))}: #{escape(yest_peak)} W (#{escape(delta(today_w, yest_w, "W"))})</div>
        </td>
      </tr>
    </table>
    """
  end

  defp chart_label_html do
    """
    <p style="font-size:11px;color:#475569;text-transform:uppercase;letter-spacing:0.05em;margin:16px 0 4px 0;">
      #{escape(gettext("Today's power curve"))}
    </p>
    """
  end

  # Drop the producer-built SVG in verbatim — the chart module has
  # already handled all escaping. Fall back to a centred paragraph
  # when the producer couldn't build a chart (no devices / no
  # readings in the window).
  defp chart_html(payload) do
    case payload[:chart_svg] || payload["chart_svg"] do
      nil ->
        "<p style=\"font-size:13px;color:#64748b;\">#{escape(gettext("No chart available"))}</p>"

      svg ->
        svg
    end
  end

  # Yield / peak delta. Either side nil → "—" (the producer couldn't
  # compute yesterday's value). Equal → "same as yesterday". Above →
  # `+diff`, below → bare diff. Format mirrors
  # `Notifications.SunDown.compare/3`.
  defp delta(nil, _, _), do: "—"
  defp delta(_, nil, _), do: "—"

  defp delta(today, yesterday, unit) when is_number(today) and is_number(yesterday) do
    cond do
      today == yesterday -> gettext("same as yesterday")
      true ->
        diff = today - yesterday
        sign = if diff > 0, do: "+", else: ""
        "#{sign}#{format_diff(diff, unit)} #{gettext("vs yesterday")}"
    end
  end

  defp format_diff(diff, "kWh"), do: Float.round(diff, 1) |> Float.to_string()
  defp format_diff(diff, "W"), do: diff |> round() |> Integer.to_string()

  # `12.4` for numbers, "—" for nil (no yesterday baseline).
  defp format_kwh(nil), do: "—"

  defp format_kwh(v) when is_number(v),
    do: v |> Float.round(1) |> Float.to_string()

  # `3,250` for numbers (thousands separator), "—" for nil.
  defp format_w(nil), do: "—"

  defp format_w(v) when is_number(v),
    do: v |> round() |> Integer.to_string() |> add_thousands_sep()

  defp add_thousands_sep(s) do
    s
    |> String.graphemes()
    |> Enum.reverse()
    |> Enum.chunk_every(3)
    |> Enum.join(",")
    |> String.reverse()
  end

  defp dashboard_url(%{dashboard_path: path}), do: DtuAppWeb.Endpoint.url() <> (path || "/dashboard")
  defp dashboard_url(_), do: DtuAppWeb.Endpoint.url() <> "/dashboard"

  # Small HTML escaper — gettext msgids ship as source strings but
  # .po translations can contain arbitrary text. Layout.escape/1
  # is private, so we keep a local copy here.
  defp escape(s) when is_binary(s),
    do:
      s
      |> String.replace("&", "&amp;")
      |> String.replace("<", "&lt;")
      |> String.replace(">", "&gt;")

  defp escape(_), do: ""
end
