import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :dtu_app, DtuAppWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :dtu_app, DtuAppWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure LiveView for production
config :phoenix_live_view,
  signing_salt: "sO3caV+W"

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Default to :info in production. Operators can override per-instance
# with `LOG_LEVEL=debug` (or `:warning` / `:error`) for ad-hoc
# performance triage — e.g. when chasing a slow mount with the
# `DASHBOARD_MOUNT_TIMING_LOG` probe or attaching an Ecto telemetry
# handler at runtime. We validate against the four standard Logger
# levels and silently fall back to :info on anything else, since
# `String.to_atom/1` would otherwise leak a fresh atom per typo
# (`:deubg` → atom leaks forever).
config :logger,
  level:
    (case System.get_env("LOG_LEVEL") do
       nil -> :info
       "emergency" -> :emergency
       "alert" -> :alert
       "critical" -> :critical
       "error" -> :error
       "warning" -> :warning
       "notice" -> :notice
       "info" -> :info
       "debug" -> :debug
       _ -> :info
     end)

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
