defmodule DtuAppWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :dtu_app

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_dtu_app_key",
    signing_salt: "qn2+Hauv",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      connect_info: [session: @session_options, user_agent: :peer],
      # For local development and testing, allow connections from any origin
      # In production with proper domains, Phoenix validates origins automatically
      check_origin: false
    ],
    longpoll: [
      # PR #244 / 2026-09-08: Phoenix's default `window_ms: 10_000`
      # is too tight for the dashboard's ~12 s mount (post-PR-#242).
      # The JS client's `connectWithFallback(fallbackThreshold = 2500)`
      # in `deps/phoenix/assets/js/phoenix/socket.js:414` gives up on
      # WebSocket after 2.5 s and switches to longpoll; the longpoll
      # GET then waits in `Phoenix.Transports.LongPoll.listen/4` for
      # a LiveView message before returning. With the 10 s default,
      # the longpoll returns 204 No Content before the mount finishes
      # at ~12 s, the client retries, and the cycle repeats for the
      # whole mount — by the time WS would have connected,
      # `phx:fallback:longpoll` has been memorised in sessionStorage
      # and the user is permanently stuck on longpoll for that
      # session. Bumping to 30 s gives the mount 2.5× headroom so a
      # single longpoll GET survives the mount and returns the first
      # LiveView message as soon as it's pushed. The LongPoll.Server
      # process's own `:shutdown_if_inactive` timer is `1.5 ×
      # window_ms` (see `long_poll_server.ex:29`), so the per-conn
      # ceiling rises to 45 s — fine at dashboard scale, worth
      # revisiting if longpoll usage ever spikes.
      window_ms: 30_000,
      connect_info: [session: @session_options]
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :dtu_app,
    gzip: not code_reloading?,
    only: DtuAppWeb.static_paths(),
    # `only_matching` lets fingerprinted URLs past the `:only` filter —
    # see `DtuAppWeb.static_match_paths/0` for the rationale. Without
    # this, `/manifest-<digest>.webmanifest` and
    # `/service-worker-<digest>.js` are 404'd by `Plug.Static` even
    # though the files exist on disk.
    only_matching: DtuAppWeb.static_match_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :dtu_app
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DtuAppWeb.Router
end
